language: php
php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: nightly
    
sudo: false

before_install:
  - composer self-update
  - npm install

install:
  - npm install
  - travis_retry composer install --no-interaction --prefer-source
  
script: npm run test:coverage